name: Build FightcadeFBNeo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup DirectX SDK
      run: |
        curl -L -o directx_sdk.exe https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe
        if not exist directx_sdk.exe exit 1
        echo "Starting DirectX SDK installation..."
        start /wait directx_sdk.exe /U /Q
        if %ERRORLEVEL% NEQ 0 (
          echo "DirectX SDK installation failed with error code %ERRORLEVEL%"
          exit 1
        )
        echo "DirectX SDK installation completed"
        echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)" >> $GITHUB_ENV
      shell: cmd

    - name: Install Perl
      run: |
        choco install activeperl --no-progress
        refreshenv
      shell: powershell

    - name: Install NASM
      run: |
        choco install nasm --no-progress
        refreshenv
      shell: powershell

    - name: Generate Games List
      run: |
        cd projectfiles
        .\games.bat
      shell: cmd

    - name: Build Solution
      run: |
        echo "DXSDK_DIR: %DXSDK_DIR%"
        msbuild "projectfiles\visualstudio-2015\fbneo_vs2015.sln" /p:Configuration=Release /p:Platform=x86 /m
      shell: cmd
      env:
        DXSDK_DIR: "C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\"

    - name: Create Build Directory
      run: |
        mkdir build
        move projectfiles\visualstudio-2015\x86\Release\fcadefbneo.exe build\
      continue-on-error: true

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fcadefbneo
        path: build\fcadefbneo.exe
