name: Build FightcadeFBNeo

on:
  push:
    branches:
      - master  # or your default branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Visual Studio 2019 Build Tools
      run: choco install -y visualstudio2019buildtools --includeRecommended --passive

    - name: Install ActivePerl
      run: choco install -y activestate-perl

    - name: Install NASM
      run: choco install -y nasm

    - name: Download and install DirectX SDK (June 2010)
      run: |
        Invoke-WebRequest -Uri 'https://download.microsoft.com/download/1/1/0/11072F7C-4CF0-4D66-8E8B-5069D3E2E615/dxsdk_redist.exe' -OutFile 'dxsdk.exe'
        Start-Process -FilePath '.\dxsdk.exe' -Args '/silent' -Wait
        # The installer may error out at the end, ignore errors

    - name: Add NASM to PATH
      shell: pwsh
      run: |
        $nasmDir = "$Env:ChocolateyInstall\lib\nasm\tools"
        $Env:Path += ";$nasmDir"
        Write-Host "PATH updated for NASM."

    - name: Set environment variables for Perl
      shell: pwsh
      run: |
        $perlPath = "$Env:ChocolateyInstall\bin"
        $Env:Path += ";$perlPath"
        Write-Host "PERL and NASM should now be in PATH."

    - name: Run 'games.bat' to populate game list
      shell: cmd
      working-directory: projectfiles\visualstudio-2015
      run: |
        call games.bat

    - name: Build the solution
      shell: cmd
      working-directory: projectfiles\visualstudio-2015
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" fbneo_vs2015.sln /p:Configuration=Release /p:Platform=Win32 /t:Rebuild

    - name: Collect build artifacts
      run: |
        mkdir artifacts
        copy projectfiles\visualstudio-2015\bin\Release\fcadefbneo.exe artifacts
        copy projectfiles\visualstudio-2015\bin\Release\*.dll artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FBNeo-Build
        path: artifacts/
