name: Windows Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install DirectX 2010 SDK
      run: |
        $ErrorActionPreference = 'continue'
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/1/9/0/1903e957-409a-4b0d-9240-1b17e0b43e0d/dxsdk_jun10.exe" -OutFile dxsdk.exe
        Start-Process -Wait -FilePath .\dxsdk.exe -ArgumentList "/Q"
      shell: pwsh

    - name: Ensure Perl is installed
      run: |
        if (-not (Get-Command perl -ErrorAction SilentlyContinue)) {
          choco install strawberryperl -y
        }
        perl -v
      shell: pwsh

    - name: Ensure NASM is installed
      run: |
        if (-not (Get-Command nasm -ErrorAction SilentlyContinue)) {
          choco install nasm -y
        }
        nasm -v
      shell: pwsh

    - name: Run games.bat
      run: |
        cd projectfiles\visualstudio-2015
        ..\..\games.bat
      shell: cmd

    - name: Build with MSBuild (Release/x86)
      run: |
        cd projectfiles\visualstudio-2015
        msbuild fbneo_vs2015.sln /p:Configuration=Release /p:Platform=x86 /m
      shell: cmd

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fbneo-windows-build
        path: |
          projectfiles/visualstudio-2015/build/*.exe
          projectfiles/visualstudio-2015/build/*.dll
