name: Build FightcadeFBNeo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Setup Visual Studio environment
      uses: microsoft/setup-msbuild@v1.1

    - name: Download DirectX SDK
      run: |
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe" -OutFile "DXSDK_Jun10.exe"
        Start-Process -FilePath "DXSDK_Jun10.exe" -ArgumentList "/U /quiet" -Wait

    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'

    - name: Install NASM
      run: |
        Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip" -OutFile "nasm.zip"
        Expand-Archive -Path "nasm.zip" -DestinationPath "C:\nasm"
        echo "C:\nasm\nasm-2.15.05" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Generate games list
      run: |
        cd ${{ github.workspace }}
        .\games.bat

    - name: Build Solution
      run: |
        cd "projectfiles\visualstudio-2015"
        msbuild fbneo_vs2015.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FightcadeFBNeo-Build
        path: build/*.exe
